project:
  type: website
  output-dir: docs

website:
  title: "Hat Yai Flood Resilience"

  sidebar:
    logo: data/logo1.jpg
    style: "docked"
    search: true
    collapse-level: 1
    tools:
      - icon: github
        href: https://github.com/sihan-yu429
      - icon: linkedin
        href: https://www.linkedin.com/in/sihan-yu-95a19b268/
    contents:
      - text: "Home"
        file: index.ipynb
      - text: "About Me"
        file: 0_Me.ipynb
      - text: "Context & Background"
        file: 1_background.ipynb
      - section: "Data Analysis"
        contents:
          - text: "Flood Exposure Analysis"
            file: 2_exposure.ipynb
          - text: "Vulnerability Analysis"
            file: Vulnerability.ipynb
          - text: "Scenario-Based Sensitivity Analysis"
            file: 4_interactive.ipynb
      - text: "Conclusion & Outlook"
        file: 5_Conclusion.ipynb

format:
  html:
    theme:
      - cosmo
      - styles.scss
    toc: true
    toc-location: right
    code-fold: true
    code-tools: true
    code-summary: "Show Code"
